import { create } from "zustand";
import { persist } from "zustand/middleware";

type Language = "vi" | "en";

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  vi: {
    "app.title": "ANH EM TUI",
    "app.tagline": "Kết nối Huyết thống - Gìn giữ Cội nguồn",
    "nav.home": "Trang chủ",
    "nav.tree": "Sơ đồ gia tộc",
    "nav.demo": "Dùng thử",
    "auth.login": "Đăng nhập",
    "auth.register": "Đăng ký",
    "auth.logout": "Đăng xuất",
    "auth.terminate": "Chấm dứt phiên làm việc",
    "tree.add_node": "Thêm thành viên",
    "tree.search": "Tìm kiếm thành viên...",
    "tree.presentation": "Trình chiếu",
    "tree.cloud_save": "Lưu trên mây",
    "tree.share": "Chia sẻ",
    "tree.sync_success": "Đã đồng bộ thành công lên mây!",
    "tree.sync_failed": "Lỗi đồng bộ: ",
    "tree.relation_update": "Cập nhật vai vế",
    "tree.relation_placeholder": "Vợ/Chồng/Con/Cha/Mẹ...",
    "tree.default_node_name": "Thành viên mới",
    "tree.default_node_job": "Chưa cập nhật",
    "tree.default_node_alias": "Người mới",
    "tree.merge_success": "Đã gộp các thành viên có cùng mối quan hệ!",
    "member.profile": "Thông tin thành viên",
    "member.personal_data": "Thông tin cá nhân",
    "member.relations": "Quan hệ",
    "member.no_relations": "Không có quan hệ nào.",
    "member.bio": "Tiểu sử / Intelligence",
    "member.bio_placeholder": "Nhập thông tin tiểu sử...",
    "member.no_bio": "Chưa có thông tin mật về đối tượng này.",
    "member.unknown": "Chưa rõ",
    "member.full_name": "Họ và tên",
    "member.gender": "Giới tính",
    "member.job": "Nghề nghiệp",
    "member.alias": "Tên thường gọi",
    "member.birth_date": "Ngày sinh",
    "member.description": "Mô tả",
    "member.is_alive": "Tình trạng",
    "member.alive": "Còn sống",
    "member.deceased": "Đã khuất",
    "member.gender.male": "Nam",
    "member.gender.female": "Nữ",
    "member.gender.other": "Khác",
    "common.save": "Lưu",
    "common.cancel": "Hủy",
    "common.delete": "Xóa",
    "common.edit": "Chỉnh sửa",
    "common.error": "Đã xảy ra lỗi thực thi!",
    "common.delete_confirm": "Bạn có chắc chắn muốn xóa không?",
    "presentation.title": "HỒ SƠ NHÂN VẬT",
    "presentation.status": "TRẠNG THÁI: ĐANG TRUY QUÉT",
    "presentation.revealed": "ĐÃ TIẾT LỘ",
    "presentation.next": "Tiếp theo",
    "presentation.prev": "Quay lại",
    "presentation.close": "Đóng",
    "admin.login.title": "Bảng Điều Khiển Mật",
    "admin.login.tagline": "Yêu cầu xác thực bảo mật",
    "admin.login.identity": "Danh tính Admin",
    "admin.login.protocol": "Giao thức truy cập",
    "admin.login.begin": "Bắt đầu kết nối",
    "admin.login.verify": "Xác minh Admin",
    "admin.login.otp_sent": "Mã OTP đã được gửi đến email bảo mật",
    "admin.login.authenticate": "Xác thực giao thức",
    "admin.login.back": "Quay lại đăng nhập",
    "admin.nav.overview": "Tổng quan",
    "admin.nav.users": "Danh sách đối tượng",
    "admin.nav.trees": "Hồ sơ lưu trữ",
    "admin.nav.collections": "Tài sản đặc biệt",
    "admin.nav.settings": "Giao thức hệ thống",
    "admin.nav.logout": "Chấm dứt phiên",
    "admin.nav.hq": "Tổng cục HQ",
    "admin.dashboard.title": "Trung tâm Chỉ huy",
    "admin.dashboard.tagline": "Thông tin hệ thống thời gian thực",
    "admin.dashboard.stats.users": "Tổng số đối tượng",
    "admin.dashboard.stats.trees": "Hồ sơ vụ việc",
    "admin.dashboard.stats.active": "Luồng hoạt động",
    "admin.dashboard.recent": "Tin tình báo mới nhất",
    "admin.dashboard.view_all": "Xem tất cả nhật ký",
    "admin.dashboard.health": "Bảng điều khiển sức khỏe",
    "admin.dashboard.storage": "Dung lượng lưu trữ",
    "admin.dashboard.api": "Tải lượng API",
    "admin.dashboard.clearance": "Mức độ an ninh",
    "admin.dashboard.encrypted": "Đã xác minh kết nối mã hóa",
    "admin.users.title": "Danh sách Đối tượng",
    "admin.users.search": "Tìm kiếm danh tính...",
    "admin.users.table.name": "Họ và tên",
    "admin.users.table.email": "Email",
    "admin.users.table.role": "Vai trò",
    "admin.users.table.joined": "Ngày tham gia",
    "admin.users.table.status": "Trạng thái",
    "admin.trees.title": "Hồ sơ Lưu trữ",
    "admin.trees.active": "Đang hoạt động",
    "admin.trees.inactive": "Đã lưu kho",
    "admin.trees.visibility": "Quyền truy cập",
    "admin.collections.title": "Tài sản Đặc biệt",
    "admin.settings.title": "Giao thức Hệ thống",
    "admin.settings.change_password": "Thay đổi Mã truy cập",
    "admin.settings.old_password": "Mã truy cập hiện tại",
    "admin.settings.new_password": "Mã truy cập mới",
    "admin.settings.update": "Cập nhật Giao thức",
    "admin.collections.create": "Triển khai Bộ sưu tập",
    "admin.collections.issue_card": "Cấp thẻ nhân vật",
    "admin.collections.manage_cards": "Quản lý Thẻ Intelligence",
    "admin.collections.assets": "Tài sản",
    "admin.collections.no_assets": "Không có tài sản trong kho",
    "admin.collections.upload_photo": "Tải ảnh lên HQ",
    "admin.collections.card_name": "Tên thẻ Intel",
    "admin.collections.char_name": "Hồ sơ nhân vật",
    "admin.collections.visual_url": "URL tài sản trực quan",
    "admin.collections.rarity": "Cấp bậc quý hiếm",
    "admin.collections.archive_name": "Tên kho lưu trữ",
    "admin.collections.intel_desc": "Mô tả tình báo",
    "admin.collections.category": "Danh mục tài sản",
    "admin.collections.commit": "Lưu vào Cơ sở dữ liệu",
    "collections.explore": "Khám phá Lưu trữ",
    "collections.accessing": "Đang truy cập hồ sơ bảo mật...",
    "collections.id_card": "THẺ ĐỊNH DANH NHÂN VẬT",
    "collections.status_active": "TRẠNG THÁI: ĐANG HOẠT ĐỘNG",
    "tree.export": "Xuất file (.aet)",
    "tree.import": "Nhập file (.aet)",
    "tree.export_success": "Đã xuất file dữ liệu gia phả!",
    "tree.import_success": "Đã nhập dữ liệu thành công!",
    "tree.import_error": "File không hợp lệ hoặc bị lỗi!",
    "tree.contribute": "Đóng góp Intel",
    "contribute.title": "Đóng góp Intel",
    "contribute.tagline": "Giao thức bảo mật",
    "contribute.assets": "Tài sản Định danh",
    "contribute.network": "Mạng lưới Tình báo",
    "contribute.submit": "Gửi xét duyệt",
    "collections.abilities": "Kỹ năng Đặc biệt",
    "collections.origin": "Nguồn gốc / Tổ chức",
  },
  en: {
    "app.title": "ANH EM TUI",
    "app.tagline": "Connecting Roots - Preserving Heritage",
    "nav.home": "Home",
    "nav.tree": "Family Tree",
    "nav.demo": "Demo",
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.logout": "Logout",
    "auth.terminate": "Terminate Session",
    "tree.add_node": "Add Member",
    "tree.search": "Search members...",
    "tree.presentation": "Presentation",
    "tree.cloud_save": "Cloud Save",
    "tree.share": "Share",
    "tree.sync_success": "Successfully synced to cloud!",
    "tree.sync_failed": "Sync failed: ",
    "tree.relation_update": "Update Relation",
    "tree.relation_placeholder": "Wife/Husband/Child/Parent...",
    "tree.default_node_name": "New Member",
    "tree.default_node_job": "Not updated",
    "tree.default_node_alias": "Newcomer",
    "tree.merge_success": "Merged identical members with same relationships!",
    "member.profile": "Subject Profile",
    "member.personal_data": "Personal Data",
    "member.relations": "Relations",
    "member.no_relations": "No known connections.",
    "member.bio": "Intelligence / Bio",
    "member.bio_placeholder": "Enter member notes or history...",
    "member.no_bio": "No classified data available for this subject.",
    "member.unknown": "Unknown",
    "member.full_name": "Full Name",
    "member.gender": "Gender",
    "member.job": "Occupation",
    "member.alias": "Alias/Nickname",
    "member.birth_date": "Birth Date",
    "member.description": "Description",
    "member.is_alive": "Status",
    "member.alive": "Alive",
    "member.deceased": "Deceased",
    "member.gender.male": "Male",
    "member.gender.female": "Female",
    "member.gender.other": "Other",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.error": "An execution error has occurred!",
    "common.delete_confirm": "Are you sure you want to delete this?",
    "presentation.title": "CHARACTER PROFILE",
    "presentation.status": "STATUS: SCANNING...",
    "presentation.revealed": "REVEALED",
    "presentation.next": "Next",
    "presentation.prev": "Previous",
    "presentation.close": "Close",
    "admin.login.title": "Classified Terminal",
    "admin.login.tagline": "Secure Authentication Required",
    "admin.login.identity": "Admin Identity",
    "admin.login.protocol": "Access Protocol",
    "admin.login.begin": "Begin Uplink",
    "admin.login.verify": "Verify Admin",
    "admin.login.otp_sent": "OTP has been sent to your classified email",
    "admin.login.authenticate": "Authenticate Protocol",
    "admin.login.back": "Back to Login",
    "admin.nav.overview": "Overview",
    "admin.nav.users": "User Registry",
    "admin.nav.trees": "Archived Cases",
    "admin.nav.collections": "Special Assets",
    "admin.nav.settings": "Terminal Protocol",
    "admin.nav.logout": "Terminate Session",
    "admin.nav.hq": "HQ Protocol",
    "admin.dashboard.title": "Command Center",
    "admin.dashboard.tagline": "Real-time system intelligence",
    "admin.dashboard.stats.users": "Total Subjects",
    "admin.dashboard.stats.trees": "Case Files",
    "admin.dashboard.stats.active": "Active Streams",
    "admin.dashboard.recent": "Recent Intelligence",
    "admin.dashboard.view_all": "View All Logs",
    "admin.dashboard.health": "Health Console",
    "admin.dashboard.storage": "Storage Capacity",
    "admin.dashboard.api": "API Load",
    "admin.dashboard.clearance": "Security Clearance",
    "admin.dashboard.encrypted": "Encrypted Connection Verified",
    "admin.users.title": "User Registry",
    "admin.users.search": "Search identities...",
    "admin.users.table.name": "Full Name",
    "admin.users.table.email": "Email",
    "admin.users.table.role": "Role",
    "admin.users.table.joined": "Joined",
    "admin.users.table.status": "Status",
    "admin.trees.title": "Archived Cases",
    "admin.trees.active": "Active",
    "admin.trees.inactive": "Archived",
    "admin.trees.visibility": "Visibility",
    "admin.collections.title": "Special Assets",
    "admin.settings.title": "Terminal Protocol",
    "admin.settings.change_password": "Change Access Code",
    "admin.settings.old_password": "Current Access Code",
    "admin.settings.new_password": "New Access Code",
    "admin.settings.update": "Update Protocol",
    "admin.collections.create": "Deploy Collection",
    "admin.collections.issue_card": "Issue Character Card",
    "admin.collections.manage_cards": "Manage Intelligence Cards",
    "admin.collections.assets": "Assets",
    "admin.collections.no_assets": "No assets in storage",
    "admin.collections.upload_photo": "Upload Photo to HQ",
    "admin.collections.card_name": "Card Intel Name",
    "admin.collections.char_name": "Character Profile",
    "admin.collections.visual_url": "Visual Asset URL",
    "admin.collections.rarity": "Rarity Grade",
    "admin.collections.archive_name": "Archive Name",
    "admin.collections.intel_desc": "Intel Description",
    "admin.collections.category": "Asset Category",
    "admin.collections.commit": "Commit to Database",
    "collections.explore": "Explore Archive",
    "collections.accessing": "Accessing Secure Records...",
    "collections.id_card": "CHARACTER IDENTIFICATION CARD",
    "collections.status_active": "STATUS: ACTIVE AGENT",
    "tree.export": "Export (.aet)",
    "tree.import": "Import (.aet)",
    "tree.export_success": "Exported genealogy data file!",
    "tree.import_success": "Data imported successfully!",
    "tree.import_error": "Invalid file or error occurred!",
    "tree.contribute": "Contribute Intel",
    "contribute.title": "Contribute Intel",
    "contribute.tagline": "Secure submission protocol",
    "contribute.assets": "Identifying Assets",
    "contribute.network": "Intelligence Network",
    "contribute.submit": "Submit for Review",
    "collections.abilities": "Tactical Abilities",
    "collections.origin": "Origin / Affiliation",
  },
};

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: "vi",
      setLanguage: (lang) => set({ language: lang }),
      t: (key) => translations[get().language][key] || key,
    }),
    {
      name: "language-storage",
    },
  ),
);
